[package]
description = "WIP: custom notebook cell cache to replace redis cache"
edition = "2021"
name = "notebook_cache"
version = "0.1.0"

[dependencies]
tokio = { version = "1.0", features = ["time", "sync"] }
tokio-util = { version = "0.7", features = ["time"] }
