name: check_lint_test
on: [push]
env:
  RUSTFLAGS: "-D warnings"

jobs:
  ci_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@v1.12.0
      - name: Check License Header
        uses: apache/skywalking-eyes/header@main

      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: cargo clippy --tests --workspace --all-targets --all-features
